[package]
name = "buffer"
version = "0.1.0"
edition = "2021"

[dependencies]
storage_engine = { path = "../storage_engine" }
common = { path = "../common" }
file_system = { path = "../file_system" }


[dev-dependencies]
